/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChatFooter: typeof import('./src/components/ChatFooter.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
  }
}
